### ISSUE TITLE
v3.0.0 giving Unresolved requirement: Import Package Error on Runtime in wso2sp-worker

### ISSUE THREAD

**Issue by SyedMHashim** [siddhi-io/siddhi-io-mqtt#47]
**Description:**
I'm using this project's bundle (jar file) in wso2sp-worker. On startup it gives an unresolved requirement error: 

```
org.osgi.framework.BundleException: Could not resolve module: siddhi-io-mqtt [202]
  Unresolved requirement: Import-Package: io.siddhi.core.config; version="[5.0.0,6.0.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
	at org.eclipse.equinox.internal.simpleconfigurator.ConfigApplier.startBundles(ConfigApplier.java:453)
	at org.eclipse.equinox.internal.simpleconfigurator.ConfigApplier.install(ConfigApplier.java:111)
	at org.eclipse.equinox.internal.simpleconfigurator.SimpleConfiguratorImpl.applyConfiguration(SimpleConfiguratorImpl.java:191)
	at org.eclipse.equinox.internal.simpleconfigurator.SimpleConfiguratorImpl.applyConfiguration(SimpleConfiguratorImpl.java:205)
	at org.eclipse.equinox.internal.simpleconfigurator.Activator.start(Activator.java:60)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:774)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:767)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:724)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:932)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:309)
	at org.eclipse.osgi.container.Module.doStart(Module.java:581)
	at org.eclipse.osgi.container.Module.start(Module.java:449)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
	at org.wso2.carbon.launcher.CarbonServer.loadInitialBundles(CarbonServer.java:242)
	at org.wso2.carbon.launcher.CarbonServer.start(CarbonServer.java:83)
	at org.wso2.carbon.launcher.Main.main(Main.java:84)

```
Previously I had been using v1.1.0 which worked just fine. It's when I started using the latest(3.0.0) version, this error showed up.

**Affected Product Version:**
v3.0.0   

**Steps to reproduce:**
1. Build the project using `mvn install`. 
2. Build the following DockerFile (just adding the snapshot jar file created as a result of `mvn install`): 
```
FROM wso2/wso2sp-worker:4.4.0
ADD --chown=wso2carbon:wso2 siddhi-io-mqtt-3.0.1-SNAPSHOT.jar /home/wso2carbon/wso2sp-4.4.0/lib/siddhi-io-mqtt-3.0.1.jar
RUN chmod 664 /home/wso2carbon/wso2sp-4.4.0/lib/siddhi-io-mqtt-3.0.1.jar
```
3. docker run -it <image_name>

**Comment by SyedMHashim** [comment]
I can see that in v3.0.0 in the component/pom.xml there is:

```
<Import-Package>
    io.siddhi.core.*;version="${siddhi.version.range}",
    io.siddhi.annotation.*;version="${siddhi.version.range}",
    io.siddhi.query.api.*;version="${siddhi.version.range}",
    *;resolution:=optional
</Import-Package>
```

while in v1.1.0 there is: 

```
<Import-Package>
    *;resolution:=optional
</Import-Package>
```
So if I just change it to the one used in v1.1.0, it does not show any error on startup. But I'm not sure if these packages are required anywhere and if it is safe to remove them.
